name: Update README with Latest Blog Posts

on:
  push:
    paths:
      - '.data/blogs.json'
      - 'update-readme.js'
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies if needed
      # - name: Install dependencies
      #   run: npm install

      - name: Update README.md with latest blog posts
        run: node update-readme.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with latest blog posts"
          file_pattern: README.md
